#!/bin/sh
#
# compile for intel ifort
#
set -x

prog1=PM25-stat
prog2=O3-stat

F77=ftn
FFLAGS="-no-wrap-margin -qopenmp -o"

LIB="-L./lib/lib -lwgrib2 -ldl -lz -lm"
# LIB="-L./lib/lib -lwgrib2 -lgfortran -ldl -lz -lm"

MOD="-I./lib/lib"


${F77} ${FFLAGS} $prog1 $prog1.f90 ${MOD} ${LIB}
${F77} ${FFLAGS} $prog2 $prog2.f90 ${MOD} ${LIB}
